### ISSUE TITLE
Can not install the Addon

### ISSUE THREAD

**Issue by Panoramiac** [Forceu/barcodebuddy-homeassistant#15]
Homeassistant version:  2023.3.1
Running on: rpi4 (Arm64)
Using an external SSD

I can not install the Addon into my Homeassistant installation (I uninstalled it recently when i migrated back from an x86 device as the addon made issues with full backups). Now on my PI I wanted to set it up again and get this error when I try to inatall the Addon:

```
23-03-09 08:42:30 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build d44967b1/aarch64-addon-bbuddy-grocy:dev-docker-based: no matching manifest for linux/arm64 in the manifest list entries
23-03-09 08:42:30 ERROR (SyncWorker_4) [supervisor.docker.addon] Build log: 
Step 1/13 : ARG BUILD_FROM
Step 2/13 : FROM ${BUILD_FROM}
```

Any suggestion what I can do, do others also have this issue?

**Comment by Panoramiac** [comment]
I could get the install workin by adding

arm64 entry

to build.json, but this is wired as aarch64 is the same as arm64 and should work. There is also an error during install:

```
11:45:32 CRITICAL (SyncWorker_5) [supervisor.utils.common] Can't parse /data/addons/git/d44967b1/build.json: extra keys not allowed @ data['build_from']['arm64']. Got 'f0rc3/barcodebuddy-docker:arm64v8-latest'
23-03-09 11:45:32 WARNING (SyncWorker_5) [supervisor.utils.common] Resetting /data/addons/git/d44967b1/build.json to default
```

Beside this I can not start the addon:
`s6-overlay-suexec: fatal: can only run as pid 1`

Which seems to be related to a init variable to be removed from the docker script, no idea where this could be locsted.

**Comment by Forceu** [comment]
Thanks for the bug report. Unfortunately this repo is community-maintained, as I do not run the hass.io image, therefore I cannot help with this issue. I will gladly merge a PR if someone fixes the problem.

**Comment by Panoramiac** [comment]
I fixed the issues for now, added init: false and now it uses an older version of the docker image, as the latest one will not start on HA. See here for further details (I will close this ticket): https://github.com/Forceu/barcodebuddy-docker/issues/26
