### ISSUE TITLE
s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by grzech1983** [Forceu/barcodebuddy-homeassistant#20]
Hello,

I'm trying to install this addon on HA 2023.3.4 and when I try to run this addon I'm getting in logs:

```
s6-overlay-suexec: fatal: can only run as pid 1
```

Any idea how to fix it?

Thanks

**Comment by mach7** [comment]
I'm also having this issue....

**Comment by CanberraTinkerer** [comment]
I'm also having this issue...

**Comment by Natclanwy** [comment]
I’m also having this issue.

**Comment by renaiku** [comment]
Same here !

**Comment by rjvbeek** [comment]
Same, following this thread

**Comment by boardnick0815** [comment]
Same here.
Is there anybody that can assist with this issue?

Thanks!

**Comment by Forceu** [comment]
Thanks for the feedback!  I will probably rewrite the docker script next week and replace the S6 script with a custom solution.

**Comment by gielk** [comment]
Awesome following this for an update.

**Comment by stjohnny22** [comment]
Following as well. - Also have what may be a stupid question. Does my HA/Grocy addon instance need to be running in Docker for this to work properly? I currently have everything installed on HomeAssistant OS - no docker that I'm aware of.

**Comment by Forceu** [comment]
I updated the script, can anyone confirm that it is working now?

**Comment by EthanGJ123** [comment]
I've just started up the addon, and the new update has fixed the issue! It's my first time using, looks good so far

**Comment by Forceu** [comment]
Thanks for the feedback!
