### ISSUE TITLE
BCB Grocy addon not showing up in HA Supervised

### ISSUE THREAD

**Issue by TMidi84** [Forceu/barcodebuddy-homeassistant#8]
Followed the steps that you have in the Read me, by adding the the repository to the Supervise /Add-on/Repositories directory. I then saved and reloaded.  The BCB add-on did not show up. I did a system restart and still not add-on. Has the repository changed by any chance? Can you please take a look into this

**Comment by Jackahack** [comment]
bump

**Comment by Jackahack** [comment]
add the url to /etc/apk/repositories and in the addon store(both). then you will be able to see it in the store. i dont know why it was not added automatically. but i tried it and it worked!

**Comment by Forceu** [comment]
Great to hear it is working now!
